### ISSUE TITLE
Other ports

### ISSUE THREAD

**Issue by promi** [ezanettin/pyAkalabeth#1]
Hi,

I saw that you are creating a port of Akalabeth in Python. I recently did this too (using Pyxel as my game engine), you can look at my efforts over at GitLab:

https://gitlab.com/promi1/pyakalabeth

Also there is another developer that has written a BASIC interpreter in Python for Akalabeth here:

https://github.com/CoBinee/akalabeth-pyxel/

**Comment by ezanettin** [comment]
Awesome! Thanks for letting me know promi.
I admit that I didn't do much searching before starting this project.
